// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQoh9TSng4vp9QHgBD6-pJYFA78kixXEg',
    appId: '1:1065866800278:web:a2bc3a2b2a5107b62766b7',
    messagingSenderId: '1065866800278',
    projectId: 'tabungan-ku-2c445',
    authDomain: 'tabungan-ku-2c445.firebaseapp.com',
    storageBucket: 'tabungan-ku-2c445.appspot.com',
    measurementId: 'G-708WZGPR42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw391p3PdSONosa_uy_2ggVwFYS1X7974',
    appId: '1:1065866800278:android:ee5309ec70d987372766b7',
    messagingSenderId: '1065866800278',
    projectId: 'tabungan-ku-2c445',
    storageBucket: 'tabungan-ku-2c445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLyvdY2EiRaTaX4zAvBfVWRwSYuHP4e8Y',
    appId: '1:1065866800278:ios:e95163a8dcee54912766b7',
    messagingSenderId: '1065866800278',
    projectId: 'tabungan-ku-2c445',
    storageBucket: 'tabungan-ku-2c445.appspot.com',
    iosBundleId: 'com.example.projectTabungan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLyvdY2EiRaTaX4zAvBfVWRwSYuHP4e8Y',
    appId: '1:1065866800278:ios:e95163a8dcee54912766b7',
    messagingSenderId: '1065866800278',
    projectId: 'tabungan-ku-2c445',
    storageBucket: 'tabungan-ku-2c445.appspot.com',
    iosBundleId: 'com.example.projectTabungan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQoh9TSng4vp9QHgBD6-pJYFA78kixXEg',
    appId: '1:1065866800278:web:246b9fc79fa682092766b7',
    messagingSenderId: '1065866800278',
    projectId: 'tabungan-ku-2c445',
    authDomain: 'tabungan-ku-2c445.firebaseapp.com',
    storageBucket: 'tabungan-ku-2c445.appspot.com',
    measurementId: 'G-750H5ZB904',
  );

}